on: [push]
name: Peekabo CI
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: "Update indexes."
        run: sudo apt-get update
      
      - name: "Install required packages."
        run: |
          sudo apt-get install -y libgtk-3-dev 
          sudo apt-get install -y libwebkit2gtk-4.0-dev 
          sudo apt-get install -y build-essential
          sudo apt-get install -y curl
          sudo apt-get install -y wget
          sudo apt-get install -y file
          sudo apt-get install -y libssl-dev
          sudo apt-get install -y libayatana-appindicator3-dev
          sudo apt-get install -y librsvg2-dev
      
      - name: "Install Tauri's CLI."
        run: cargo install tauri-cli
          
      - name: "Build Peekabo."
        uses: actions-rs/cargo@v1
        with:
          command: tauri
          args: build
